// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_best_time__highest = "CgkIrvvlo4wZEAIQBw"; // <GPGSID>
        public const string leaderboard_high_score__lowest = "CgkIrvvlo4wZEAIQBg"; // <GPGSID>
        public const string achievement_easy_achievment = "CgkIrvvlo4wZEAIQCw"; // <GPGSID>
        public const string achievement_simple_but_hidden_achievment = "CgkIrvvlo4wZEAIQCg"; // <GPGSID>
        public const string achievement_moderate_achievment = "CgkIrvvlo4wZEAIQDA"; // <GPGSID>
        public const string achievement_simple_achievment = "CgkIrvvlo4wZEAIQCQ"; // <GPGSID>
        public const string achievement_hard_achievment = "CgkIrvvlo4wZEAIQDQ"; // <GPGSID>
        public const string leaderboard_best_time__lowest = "CgkIrvvlo4wZEAIQCA"; // <GPGSID>
        public const string leaderboard_high_score__highest = "CgkIrvvlo4wZEAIQBQ"; // <GPGSID>

}

